name=input("Enter name ")
print(f"You have entered {name} type is {type(name)}")
age=input("Enter age ")
new_age=int(age)
print(f"You have entered {age} type is {type(age)} type of new age {type(new_age)}")
per=input("Enter percentage ")
new_per=float(per)
print(f"You have entered {per} type is {type(per)} type of new per {type(new_per)}")